# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Pointwise Confidence Intervals under Current Status data
#'
#'@description The function ComputeConfIntervals computes pointwise confidence intervals for the distribution function under current status data.
#'The confidence intervals are based on the Smoothed Maximum likelihood Estimator and constructed using the nonparametric bootstrap.
#'
#'@param data Dataframe with three variables:
#'\describe{
#'     \item{t}{Observation points t sorted in ascending order. All observations need to be positive. The total number of unique observation points equals \code{length(t)}.}
#'     \item{freq1}{Frequency of observation t satisfying \eqn{x \le t}.
#'                   The total number of observations with censoring indicator \eqn{\delta =1} equals \code{sum(freq1)}. }
#'     \item{freq2}{Frequency of observation t. The sample size equals \code{sum(freq2)}. If no tied observations are present in the data \code{length(t)} equals \code{sum(freq2)}. }
#'}
#'
#'@param x numeric vector containing the points where the confidence intervals are computed.
#'         This vector needs to be contained within the observation interval: \eqn{t[1] < min(x) \le max(x) < t[n]}.
#'
#'@param alpha confidence level of pointwise confidence intervals
#'
#'@return List with 4 variables:
#'
#'\enumerate{
#'     \item{MLE }{ Maximum Likelihood Estimator}
#'     \item{SMLE }{ Smoothed Maximum Likelihood Estimator in x }
#'     \item{h }{ data-driven bandwidth choice for each point in x}
#'     \item{CI }{ pointwise confidence interval for each points in x}
#' }
#'
#' @details In the current status model, the variable of interest \eqn{X} with distribution function \eqn{F} is not observed directly.
#'A censoring variable \eqn{T} is observed instead together with the indicator \eqn{\Delta = (X \le T)}.
#' ComputeConfIntervals computes the pointwise \code{1-alpha} bootstrap confidence intervals around the SMLE of \eqn{F} based on a sample of size \code{n <- sum(data$freq2)} from the observable random  vector \eqn{(T, \Delta)}.
#' The bandwidth used for estimating the SMLE at a point in the vector x is obtained by minimizing the pointwise Mean Squared Error using the subsampling pricinciple in combination with undersmoothing.
#'
#' @seealso \code{vignette("curstatCI")}
#'
#'@examples
#'library(Rcpp)
#'library(curstatCI)
#'
#'# sample size
#'n <- 1000
#'
#'# Uniform data  U(0,2)
#'set.seed(2)
#'y <- runif(n,0,2)
#'t <- runif(n,0,2)
#'delta <- as.numeric(y <= t)
#'
#'A<-cbind(t[order(t)], delta[order(t)], rep(1,n))
#'grid<-seq(0.01,1.99 ,by = 0.01)
#'
#'# pointwise confidence intervals at grid points:
#'out<-ComputeConfIntervals(data = A,x =grid,alpha = 0.05)
#'
#'left <- out$CI[,1]
#'right <- out$CI[,2]
#'
#'plot(grid, out$SMLE,type ='l', ylim=c(0,1), main= "",ylab="",xlab="",las=1)
#'lines(grid, left, col = 4)
#'lines(grid, right, col = 4)
#'segments(grid,left, grid, right)
#'
#'@references The nonparametric bootstrap for the current status model, Groeneboom, P. and Hendrickx, K. Electronical Journal of Statistics (2017)
#'@export
ComputeConfIntervals <- function(data, x, alpha) {
    .Call('curstatCI_ComputeConfIntervals', PACKAGE = 'curstatCI', data, x, alpha)
}

#'@title Maximum Likelihood Estimator
#'
#'@description The function ComputeMLE computes the Maximum Likelihood Estimator of the distribution function under current status data.
#'
#'@param data Dataframe with three variables:
#'\describe{
#'     \item{t}{Observation points t sorted in ascending order. All observations need to be positive. The total number of unique observation points equals \code{length(t)}.}
#'     \item{freq1}{Frequency of observation t satisfying \eqn{x \le t}.
#'                   The total number of observations with censoring indicator \eqn{\delta =1} equals \code{sum(freq1)}. }
#'     \item{freq2}{Frequency of observation t. The sample size equals \code{sum(freq2)}. If no tied observations are present in the data \code{length(t)} equals \code{sum(freq2)}. }
#'}
#'
#'@details In the current status model, the variable of interest \eqn{X} with distribution function \eqn{F} is not observed directly.
#'A censoring variable \eqn{T} is observed instead together with the indicator \eqn{\Delta = (X \le T)}.
#' ComputeMLE computes the MLE of \eqn{F} based on a sample of size \code{n <- sum(data$freq2)} from the observable random  vector \eqn{(T, \Delta)}.
#'
#'
#'
#'@return Dataframe with two variables :
#'\describe{
#'     \item{x}{jumplocations of the MLE}
#'     \item{mle}{MLE evaluated at the jumplocations}
#' }
#'
#'@references The nonparametric bootstrap for the current status model, Groeneboom, P. and Hendrickx, K. Electronical Journal of Statistics (2017)
#'
#'@seealso \code{\link{ComputeConfIntervals}}
#'
#'
#'@examples
#'library(Rcpp)
#'library(curstatCI)
#'
#'# sample size
#'n <- 1000
#'
#'# Uniform data  U(0,2)
#'set.seed(2)
#'y <- runif(n,0,2)
#'t <- runif(n,0,2)
#'delta <- as.numeric(y <= t)
#'
#'A<-cbind(t[order(t)], delta[order(t)], rep(1,n))
#'mle <-ComputeMLE(A)
#'plot(mle$x, mle$mle,type ='s', ylim=c(0,1), main= "",ylab="",xlab="",las=1)
#'
#'@export
ComputeMLE <- function(data) {
    .Call('curstatCI_ComputeMLE', PACKAGE = 'curstatCI', data)
}

#'@title Smoothed Maximum Likelihood Estimator
#'
#'@description The function ComputeSMLE computes the Smoothed Maximum Likelihood Estimator of the distribution function under current status data.
#'
#'@param data Dataframe with three variables:
#'\describe{
#'     \item{t}{Observation points t sorted in ascending order. All observations need to be positive. The total number of unique observation points equals \code{length(t)}.}
#'     \item{freq1}{Frequency of observation t satisfying \eqn{x \le t}.
#'                   The total number of observations with censoring indicator \eqn{\delta =1} equals \code{sum(freq1)}. }
#'     \item{freq2}{Frequency of observation t. The sample size equals \code{sum(freq2)}. If no tied observations are present in the data \code{length(t)} equals \code{sum(freq2)}. }
#'}
#'
#'@param h bandwidth
#'
#'@param x numeric vector
#'
#'@details In the current status model, the variable of interest \eqn{X} with distribution function \eqn{F} is not observed directly.
#'A censoring variable \eqn{T} is observed instead together with the indicator \eqn{\Delta = (X \le T)}.
#' ComputeSMLE computes the SMLE of \eqn{F} based on a sample of size \code{n <- sum(data$freq2)} from the observable random  vector \eqn{(T, \Delta)}.
#' The same bandwidth h is used for all points in the vector x.
#' A selection procedure to obtain a data-driven (and possibly different) bandwidth choice for each point in the vector x is used in the function \code{\link{ComputeConfIntervals}}.
#'
#'@return SMLE(x)
#'
#'@references The nonparametric bootstrap for the current status model, Groeneboom, P. and Hendrickx, K. Electronical Journal of Statistics (2017)
#'
#'@seealso \code{\link{ComputeConfIntervals}}
#'
#'@examples
#'library(Rcpp)
#'library(curstatCI)
#'
#'# sample size
#'n <- 1000
#'
#'# Uniform data  U(0,2)
#'set.seed(2)
#'y <- runif(n,0,2)
#'t <- runif(n,0,2)
#'delta <- as.numeric(y <= t)
#'
#'A<-cbind(t[order(t)], delta[order(t)], rep(1,n))
#'grid <-seq(0,2 ,by = 0.01)
#'h<-2*n^-0.2
#'
#'smle <-ComputeSMLE(A,grid,h)
#'plot(grid, smle,type ='l', ylim=c(0,1), main= "",ylab="",xlab="",las=1)
#'
#'
#'@export
ComputeSMLE <- function(data, x, h) {
    .Call('curstatCI_ComputeSMLE', PACKAGE = 'curstatCI', data, x, h)
}

