# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Confidence Intervals
#'@param input DataFrame with three variables:
#'\describe{
#'     \item{xx}{Observation points t sorted in ascending order}
#'     \item{freq1}{Frequency of observation t satisfying \eqn{y \le t}}
#'     \item{freq2}{Frequency of observation t}
#'}
#'@param x numeric vector
#'@param alpha level for confidence intervals
#'@return List with 4 variables:
#'\enumerate{
#'     \item{MLE}{ maximum likelihood estimator}
#'     \item{SMLE}{ smoothed maximum likelihood estimator}
#'     \item{h}{ local bandwidths for points of grid}
#'     \item{CI}{ confidence intervals on points of grid}
#'     }
#'@export
ComputeConfIntervals <- function(input, x, alpha) {
    .Call('curstatCI_ComputeConfIntervals', PACKAGE = 'curstatCI', input, x, alpha)
}

#'@title Maximum Likelihood Estimator
#'@param data DataFrame with three variables:
#'\describe{
#'     \item{t}{Observation points t sorted in ascending order}
#'     \item{freq1}{Frequency of observation t satisfying \eqn{y \le t}}
#'     \item{freq2}{Frequency of observation t}
#'}
#'@return DataFrame with two variables :
#'\describe{
#'     \item{x}{jumplocations of the MLE}
#'     \item{mle}{MLE evaluated at the jumplocations}
#' }
#'@export
ComputeMLE <- function(data) {
    .Call('curstatCI_ComputeMLE', PACKAGE = 'curstatCI', data)
}

#'@title Smoothed Maximum Likelihood Estimator
#'@param data DataFrame with three variables:
#'\describe{
#'     \item{t}{Observation points t sorted in ascending order}
#'     \item{freq1}{Frequency of observation t satisfying \eqn{y \le t}}
#'     \item{freq2}{Frequency of observation t}
#'}
#'@param h bandwidth
#'@param x a number or vector
#'@return SMLE(x)
#'
#'@export
ComputeSMLE <- function(data, x, h) {
    .Call('curstatCI_ComputeSMLE', PACKAGE = 'curstatCI', data, x, h)
}

